// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package plus.vertx.test.beanCopy.protoBean;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:plus.vertx.test.beanCopy.protoBeant.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int32 status = 2;</code>
   * @return The status.
   */
  int getStatus();
}
