// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package plus.vertx.test.beanCopy.protoBean;

/**
 * Protobuf enum {@code plus.vertx.test.beanCopy.protoBeant.ServingStatus}
 */
public enum ServingStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN = 0;</code>
   */
  UNKNOWN(0),
  /**
   * <code>SERVING = 1;</code>
   */
  SERVING(1),
  /**
   * <code>NOT_SERVING = 2;</code>
   */
  NOT_SERVING(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN = 0;</code>
   */
  public static final int UNKNOWN_VALUE = 0;
  /**
   * <code>SERVING = 1;</code>
   */
  public static final int SERVING_VALUE = 1;
  /**
   * <code>NOT_SERVING = 2;</code>
   */
  public static final int NOT_SERVING_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static ServingStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ServingStatus forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN;
      case 1: return SERVING;
      case 2: return NOT_SERVING;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ServingStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
          ServingStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ServingStatus>() {
          public ServingStatus findValueByNumber(int number) {
            return ServingStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return plus.vertx.test.beanCopy.protoBean.Hello.getDescriptor().getEnumTypes().get(0);
  }

  private static final ServingStatus[] VALUES = values();

  public static ServingStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ServingStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:plus.vertx.test.beanCopy.protoBeant.ServingStatus)
}

